[package]
name = "ktls-recvmsg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
cfg-if = "1.0.0"
libc = { version = "0.2.148", features = ["const-extern-fn", "extra_traits"] }
