name: test

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true
      CARGO_INCREMENTAL: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up sccache (part 1)
        uses: mozilla-actions/sccache-action@v0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up sccache (part 2)
        run: sccache --start-server
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-llvm-cov,cargo-nextest
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          cargo clippy
          cargo test